<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @description:
 *
 */
?>
<?php
$_items = $block->getReviewsCollection()->getItems();
$format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
?>
<?php if (count($_items)):?>
    <div class="block review-list" id="customer-reviews">
        <div class="block-title">
            <strong><?php /* @escapeNotVerified */ echo __('Customer Reviews') ?></strong>
        </div>
        <div class="block-content">
            <div class="toolbar review-toolbar">
                <?php echo $block->getChildHtml('toolbar') ?>
            </div>
            <ol class="items review-items">
                <?php foreach ($_items as $_review):?>
                    <li class="item review-item" itemscope itemprop="review" itemtype="http://schema.org/Review">
                        <div class="review-title" itemprop="name"><?php echo $block->escapeHtml($_review->getTitle()) ?></div>
                        <?php if (count($_review->getRatingVotes())): ?>
                            <div class="review-ratings">
                                <?php foreach ($_review->getRatingVotes() as $_vote): ?>
                                    <div class="rating-summary item" itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                                        <span class="label rating-label"><span><?php echo $block->escapeHtml($_vote->getRatingCode()) ?></span></span>
                                        <div class="rating-result" title="<?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%">
                                            <meta itemprop="worstRating" content = "1"/>
                                            <meta itemprop="bestRating" content = "100"/>
                                            <span style="width:<?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%">
                                                <span itemprop="ratingValue"><?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%</span>
                                            </span>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        <?php endif; ?>
                        <div class="review-content" itemprop="description">
                            <?php echo nl2br($block->escapeHtml($_review->getDetail())) ?>
                        </div>
                        <div class="review-details">
                            <p class="review-author">
                                <span class="review-details-label"><?php /* @escapeNotVerified */ echo __('Review by')?></span>
                                <strong class="review-details-value" itemprop="author"><?php echo $block->escapeHtml($_review->getNickname()) ?></strong>
                            </p>
                            <p class="review-date">
                                <span class="review-details-label"><?php /* @escapeNotVerified */ echo __('Posted on') ?></span>
                                <time class="review-details-value" itemprop="datePublished" datetime="<?php /* @escapeNotVerified */ echo $block->formatDate($_review->getCreatedAt(), $format) ?>"><?php /* @escapeNotVerified */ echo $block->formatDate($_review->getCreatedAt(), $format) ?></time>
                            </p>
                            <div class="review-helpful">
                                <div class="review-like">
                                    <span class="test"><?php echo Matej\bReviews\Helper\Data::getReviewLikes($_review->getId()); ?></span>
                                    <a href="javascript:void(0);" onclick="javascript:likeButton(this, '<?php echo $_review->getId() ?>', 1)"><i class="fa fa-thumbs-up" aria-hidden="true"></i></a>
                                </div>
                                <div class="review-dislike">
                                    <span><?php echo Matej\bReviews\Helper\Data::getReviewDislikes($_review->getId()); ?></span>
                                    <a href="javascript:void(0);" onclick="javascript:likeButton(this, '<?php echo $_review->getId() ?>', 2)"><i class="fa fa-thumbs-down" aria-hidden="true"></i></a>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
            <div class="toolbar review-toolbar">
                <?php echo $block->getChildHtml('toolbar') ?>
            </div>
        </div>
    </div>
<?php endif;?>

<script>
    function likeButton(domElement, productID, statusID) {
        require(["jquery"], function($) {

            // Incrementing (Dis)likes Value
            $(domElement).prev().text(parseInt($(domElement).prev().text(), 10) + 1);

            // Disabling Current Button
            $(domElement).prop("onclick", null).css("color", "#9f9f9f");

            if(statusID === 1) {
                // Disabling Dislike Button
                $(domElement).parents(":eq(1)").find(".review-dislike").find("a").prop("onclick", null).css("color", "#9f9f9f");
            } else {
                // Disabling Like Button
                $(domElement).parents(":eq(1)").find(".review-like").find("a").prop("onclick", null).css("color", "#9f9f9f");
            }

            $.ajax({
                type: 'post',
                url: "<?php echo $block->getUrl("reviewlike/index/index"); ?>",
                data: { productid: productID, statusid: statusID },
                dataType: 'json'
                /*
                    // NOTE: Remember to add , next to 'json'!
                    success: function(data, textStatus ){
                        alert(data); // Debugging Ajax Call
                    },
                    error: function(xhr, textStatus, errorThrown){
                        alert(errorThrown); // Debugging Ajax Call
                    }
                */
            });
        });
    }
</script>